### ISSUE TITLE
Support custom vLLM build

### ISSUE THREAD

**Issue by viktor-ferenczi** [runpod-workers/worker-vllm#10]
Since vLLM is developing real fast it would be useful to have a command line option (`--build-arg`) to point to a locally built vLLM package to use instead of a specific version. It would allow for using local builds from `main` or PR branches, also for using modified versions of vLLM.

**Comment by nicolasembleton** [comment]
You can just update builder/requirements.txt to suit your needs, or update the builder/setup.sh to check if there's a vLLM package to build and build it with ENV args if there is. It wouldn't be hard to pull of. (but I am not sure I'd see a particular use case personally)

**Comment by alpayariyak** [comment]
The worker currently uses our modified fork of vllm, to make sure it works with serverless. I'm not sure if adding something like this will create more confusion than utility for the general user base
