### ISSUE TITLE
'NoneType' object has no attribute 'headers' (completions endpoint)

### ISSUE THREAD

**Issue by Permafacture** [runpod-workers/worker-vllm#104]
When trying to use the completions endpoint (rather than chat_completions) on a vLLM runpod serverless instance I get a server error. This happens with all models that I've tried. The chat_completions endpoint works as expected.

This example from the vLLM quick start shows the issue
```
from openai import OpenAI

# Modify OpenAI's API key and API base to use vLLM's API server.
openai_api_key = "<MyApiKey>"
openai_api_base = "https://api.runpod.ai/v2/<endpoint_id>/openai/v1"
client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)
completion = client.completions.create(model="Phi-3-small-8k-instruct",
                                      prompt="San Francisco is a")
print("Completion result:", completion)
```

On the client side I get a 500 Error response. On the Server I can see the error is `'NoneType' object has no attribute 'headers'`

This is using the most recent vLLM 0.5.4

**Comment by Permafacture** [comment]
Update I installed vLLM 0.5.4 locally through pip and did not have this issue. It's specific to the runpod worker

**Comment by Juhong-Namgung** [comment]
Same issue in vLLM 0.5.3 (runpod/worker-v1-vllm:stable-cuda12.1.0)

**Comment by TimPietrusky** [comment]
@Permafacture thanks for reporting this problem. 

We are working on resolving this, I will keep you updated!

**Comment by prashantjoshi22** [comment]
Is the issue resolved ?

**Comment by jamorell** [comment]
Same issue in vLLM 0.5.4 on runpod. Any news about this?

**Comment by naaviii12345** [comment]
We are also getting consistent issues from Runpod , and it is hampering our production pipelines . I think this issue is pending since 2-3 weeks , and the support team is not responding . 

I think , it is the high time to switch from runpod to any other trustful vendor

**Comment by TimPietrusky** [comment]
@ericflo @naaviii12345 @jamorell @Permafacture @Juhong-Namgung @prashantjoshi22 

We just released a bug fix: `runpod/worker-v1-vllm:v1.3.1dev-cuda12.1.0`. Can you please check if this is working for you?

**Comment by Permafacture** [comment]
How do I try this on Runpod? I've only used the quick deploy for the vllm worker

**Comment by pandyamarut** [comment]
This has been fixed.

**Comment by prashantjoshi22** [comment]
Thanks team :-)
