### ISSUE TITLE
support for quantization? 

### ISSUE THREAD

**Issue by WillReynolds5** [runpod-workers/worker-vllm#12]
I am wondering if there is a way to load a model with quantization? I can load my model with awq quantization with vllm api_server but I am am not seeing support for serverless endpoints. 

Thanks!

**Comment by willsamu** [comment]
I have added the implementation and opened a pr: https://github.com/runpod-workers/worker-vllm/pull/16
Only tested on two models, but works for me. Let's wait for the maintainers response.

**Comment by WillReynolds5** [comment]
Thank you!!

**Comment by alpayariyak** [comment]
Quantization now supported on the main branch. Thanks!
