### ISSUE TITLE
Serverless VLLM Runpod deploying facebook/opt-125m model on its own.

### ISSUE THREAD

**Issue by kunalchamoli** [runpod-workers/worker-vllm#128]
I am trying to deploy meta-llama/Llama-3.1-70B-Instruct using serverless VLLM in runpod, I have correctly added "HuggingFace Model" and "Hugging Face Token" with vllm version "0.6.3(latest)" . 
But it always shows and deploys facebook/opt-125 instead.

**Comment by pandyamarut** [comment]
Thanks @kunalchamoli  for calling it out. this is fixed.
