### ISSUE TITLE
PSA: Things break if you don't set TOKENIZER variable

### ISSUE THREAD

**Issue by Palmik** [runpod-workers/worker-vllm#14]
For some reason, when you don't specify it, it results in tokenizer being `''` rather than `None`. Adding the following snippet fixes it:

```
if len(TOKENIZER) == 0:
    TOKENIZER = None
```

**Comment by ricardo-st** [comment]
Good find, was going crazy about this.
Would be even better to check for the following:
```python
if not TOKENIZER:
    TOKENIZER = None
```
As this handles the case where TOKENIZER is already set to None, 0, or any other non standard way.

**Comment by ashleykleynhans** [comment]
> Good find, was going crazy about this. Would be even better to check for the following:
> 
> ```python
> if not TOKENIZER:
>     TOKENIZER = None
> ```
> 
> As this handles the case where TOKENIZER is already set to None, 0, or any other non standard way.

My PR does exactly this, would be nice if it could get merged:
https://github.com/runpod-workers/worker-vllm/pull/17/files
