### ISSUE TITLE
Docker image is taking too much time to build

### ISSUE THREAD

**Issue by xianchenw** [runpod-workers/worker-vllm#37]
![image](https://github.com/runpod-workers/worker-vllm/assets/96175229/c9b3dbd5-0883-4876-ac44-4fb2c38a64cc)

Hi guys, I am trying to build the Docker image, but it is taking too long during the 'install vllm' step. Is this normal? Is there any solution to resolve it?

`python3.11 -m pip install -e git+https://github.com/runpod/vllm-fork-for-sls-worker.git@cuda-11.8#egg=vllm`

**Comment by alpayariyak** [comment]
Just pushed an update to address this, let me know if you’re still facing the issue

**Comment by xianchenw** [comment]
> Just pushed an update to address this, let me know if you’re still facing the issue

https://github.com/runpod-workers/worker-vllm/commit/5aecb628702777356778dbb871d87d790279200d

It seems like wrong branch name

![image](https://github.com/runpod-workers/worker-vllm/assets/96175229/a0e8c847-d770-4295-85de-41fb1357b6da)

Do you mean `old-11.8` and `old-12.1` ?

![image](https://github.com/runpod-workers/worker-vllm/assets/96175229/e714f9b7-45ce-4609-8895-8eb449f6c463)

**Comment by alpayariyak** [comment]
Yes, that’s the one. My sincere apologies!

**Comment by xianchenw** [comment]
![image](https://github.com/runpod-workers/worker-vllm/assets/96175229/d11b380b-d5be-46dd-87a8-d6a603dc87f5)
Still take too much time :(((

**Comment by alpayariyak** [comment]
Try adding something like this before the build and adjust the values based on your system:

ENV MAX_JOBS=48 # The number of CPU cores you have
ENV NVCC_THREADS=1024 # Changes depending on GPU

**Comment by alpayariyak** [comment]
Try out 0.2.0, you no longer need to compile vLLM, so the build should be very fast.

**Comment by xianchenw** [comment]
I will try! Thanks for your help!
