### ISSUE TITLE
Cannot run Mixtral 8x7B Instruct AWQ

### ISSUE THREAD

**Issue by ddemillard** [runpod-workers/worker-vllm#49]
I have successfully been able to run mistral/Mistral-7b-Instruct in both original and quantized (awq) format on runpod serverless using this repo. However, when I try to run Mixtral AWQ, I simply get no text output from the chat response with no errors. I have tried many times with various configurations including:

- Running on 80gb GPUs instead of 48GB
- Supplying the Mixtral template format in the prompt e.g. `<s>[INST] MESSAGE [/INST]`
- Using messages instead of prompt
- Rebuilding the image to double check parameters
- Increasing the number of output tokens
- Toggling on and off the chat template

Nothing so far has worked and I would appreciate any new ideas. I really love the concept of runpod and serverless GPUs for LLMs but this issue has me stumped.

Please see the build configuration, example input, and incorrect outputs below:

Build command:
docker build --network=host -t danielallium/mixtral-instruct-awq:v0.4 --build-arg MODEL_NAME="TheBloke/Mixtral-8x7B-Instruct-v0.1-AWQ" --build-arg BASE_PATH="/models" --build-arg WORKER_CUDA_VERSION="12.1.0" --build-arg QUANTIZATION=awq .

Input:
{
  "input": {
    "prompt": "Hello World"
  }
}

Output without errors:
{
  "delayTime": 81440,
  "executionTime": 1561,
  "id": "334efe4a-9039-47e6-8dec-ec772df94370-u1",
  "output": [
    {
      "choices": [
        {
          "tokens": [
            ""
          ]
        }
      ],
      "usage": {
        "input": 3,
        "output": 16
      }
    }
  ],
  "status": "COMPLETED"
}

Note that "tokens" using any other LLM will return a non-empty string. You can also test my docker image directly as it is public at: anielallium/mixtral-instruct-awq:v0.4 

This build works just fine with the above prompt though:
docker build --network=host -t danielallium/mistral-7b-instruct-awq:v0.2 --build-arg MODEL_NAME="TheBloke/Mistral-7B-Instruct-v0.2-AWQ" --build-arg BASE_PATH="/models" --build-arg WORKER_CUDA_VERSION="12.1.0" --build-arg QUANTIZATION=awq .

**Comment by alpayariyak** [comment]
Hi,
Try setting `TRUST_REMOTE_CODE` env var in the template to `1`

**Comment by ddemillard** [comment]
Hi, I just tried this and the problem persists. There doesn't really seem to be a problem with loading the models. The models seem to load and initialize fine. When I submit a request, the gpu utilization goes up and seems like it is processing, it even says that tokens were generated via the "Output" number but nothing is ever generated. It is always empty. Again, I can get different models to work just fine with the exact same configuration so I'm not really sure what the problem is. 

Here are the logs, let me know if you would like me to expand anything:
![image](https://github.com/runpod-workers/worker-vllm/assets/104535803/fc3fe238-0bf1-4ee8-88e9-2db1300c2518)

**Comment by alpayariyak** [comment]
Found this issue: https://github.com/vllm-project/vllm/issues/2833

One user suggests changing chat template, you can do this with env var `CUSTOM_CHAT_TEMPLATE`

**Comment by ddemillard** [comment]
It appears that this particular hugging face model is broken. 

Use this version instead: casperhansen/mixtral-instruct-awq

Everything works fine with that version. Thanks for you help and you can close this issue.

**Comment by alpayariyak** [comment]
That's great to hear! Try out the new worker vLLM version that now is OpenAI compatible when you get the chance :)
