### ISSUE TITLE
Support for GPT3 based models

### ISSUE THREAD

**Issue by letajmal** [runpod-workers/worker-vllm#54]
Requesting for GPT3 based model support in worker

**Comment by alpayariyak** [comment]
Hi,
GPT-3 is not open source. 

The following GPT architectures are supported:
- GPT-2 (`gpt2`, `gpt2-xl`, etc.)
- GPT BigCode (`bigcode/starcoder`, `bigcode/gpt_bigcode-santacoder`, etc.)
- GPT-J (`EleutherAI/gpt-j-6b`, `nomic-ai/gpt4all-j`, etc.)
- GPT-NeoX (`EleutherAI/gpt-neox-20b`, `databricks/dolly-v2-12b`, `stabilityai/stablelm-tuned-alpha-7b`, etc.)
