### ISSUE TITLE
Incorrect path_or_model_id

### ISSUE THREAD

**Issue by Sapessii** [runpod-workers/worker-vllm#75]
Hi!

In the last few hours I'm getting this error while pulling any image from hugging face:

`OSError: Incorrect path_or_model_id: ''. Please provide either the path to a local folder or the repo_id of a model on the Hub.`

I am using the standard vllm template from runpod serverless.

Thank you!

**Comment by rafa-9** [comment]
same error @alpayariyak

**Comment by ashleykleynhans** [comment]
I am getting the same error @alpayariyak

**Comment by ashleykleynhans** [comment]
My model isn't pulled from Hugging Face though, it already exists on my Network Storage, I downloaded it manually and didn't use the vllm template in the "Explore" section to create my vllm endpoint, I created my template and endpoint manually.

**Comment by Sapessii** [comment]
I have another serverless with network storage and builtin model and keeps getting "out of memory" while previously it was working smoothly

**Comment by ashleykleynhans** [comment]
@Sapessii thats a different issue, please don't hijack this issue with unrelated issues.

**Comment by alpayariyak** [comment]
Are you all using the same model @Sapessii  @rafa-9  @ashleykleynhans

**Comment by Sapessii** [comment]
I tried with

1. cognitivecomputations/dolphin-2.9.1-llama-3-8b
2. NousResearch/Hermes-2-Pro-Mistral-7B
3. mlabonne/NeuralHermes-2.5-Mistral-7B

**Comment by ashleykleynhans** [comment]
I am using `meta-llama/Meta-Llama-3-70B`

**Comment by alpayariyak** [comment]
Seems Huggingface made changes on their end for Tokenizers that breaks all Worker vLLM deployments, on it

**Comment by ashleykleynhans** [comment]
My cognitivecomputations/dolphin-2.9.1-llama-3-8b` endpoint is actually working, @Sapessii

**Comment by ashleykleynhans** [comment]
> Seems Huggingface made changes on their end for Tokenizers that breaks all Worker vLLM deployments, on it

Thanks, so what is the solution? Do they need to fix it or can we do something to fix it, or must you do something to fix it?

**Comment by ashleykleynhans** [comment]
Multiple eople are reporting on Discord that their environment variables for their serverless endpoints just started getting lost.  Could that not be the cause of this issue since the worker is heavily dependent on environment variables?

**Comment by ashleykleynhans** [comment]
Seems to be fine now that the issue with the environment variables getting lost is resolved, but I had to scale my workers down to zero and back up again so that the environment variables could be correctly applied and now I am no longer getting this error.

**Comment by alpayariyak** [comment]
Yes, I found that the environment variables set in the template are not read by the worker, we reverted the change on our end about an hour ago! We're very sorry for any inconvenience, please contact us if it affected your production.
